# Generated by Django 4.2.21 on 2026-02-13 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('revenue', '0002_carcategory_car_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='other_details',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='transaction_catagory',
            field=models.CharField(choices=[('country', 'Country'), ('out_side', 'Out_Side')], default=None, max_length=20),
            preserve_default=False,
        ),
    ]
