# Generated by Django 4.2.21 on 2026-02-13 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('revenue', '0003_order_other_details_order_transaction_catagory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='transaction_catagory',
            field=models.CharField(choices=[('local', 'Local'), ('foreign', 'Foreign')], max_length=20),
        ),
    ]
