# Generated by Django 4.2.21 on 2026-02-14 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('revenue', '0004_alter_order_transaction_catagory'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_status',
            field=models.CharField(blank=True, choices=[('pending', 'Cending'), ('completed', 'Completed')], default='pending', max_length=20),
        ),
    ]
