# Generated by Django 4.2.21 on 2026-02-14 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('revenue', '0005_order_payment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_status',
            field=models.CharField(blank=True, choices=[('pending', 'Pending'), ('completed', 'Completed')], default='pending', max_length=20),
        ),
    ]
