# Generated by Django 4.2.21 on 2026-02-16 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('revenue', '0008_car_description_customer_companyaccount_auction'),
    ]

    operations = [
        migrations.AddField(
            model_name='carcategory',
            name='company',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
