# Generated by Django 4.2.21 on 2026-02-16 18:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('revenue', '0009_carcategory_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='auction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='revenue.auction'),
        ),
        migrations.AddField(
            model_name='order',
            name='company_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='revenue.companyaccount'),
        ),
        migrations.AddField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='revenue.customer'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='car_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_items', to='revenue.carcategory'),
        ),
    ]
