# Generated by Django 4.2.21 on 2026-02-17 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('revenue', '0010_order_auction_order_company_account_order_customer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='swift_code',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
