# Generated by Django 4.2.21 on 2026-02-17 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('revenue', '0011_customer_swift_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='name',
        ),
        migrations.AlterField(
            model_name='carcategory',
            name='company',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='carcategory',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
