# Generated by Django 4.2.21 on 2026-02-18 00:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('revenue', '0012_remove_car_name_alter_carcategory_company_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Saler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.TextField()),
                ('phone', models.CharField(max_length=50)),
                ('account_number', models.CharField(max_length=100)),
                ('branch_code', models.CharField(max_length=50)),
                ('bank_name', models.CharField(max_length=200)),
                ('swift_code', models.CharField(blank=True, max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'salers',
            },
        ),
        migrations.AddField(
            model_name='order',
            name='saler',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='revenue.saler'),
        ),
    ]
