# Generated by Django 4.2.21 on 2026-02-18 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('revenue', '0014_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='deposit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='withdraw',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
