# Generated by Django 4.2.21 on 2026-02-19 00:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('revenue', '0015_transaction_deposit_alter_transaction_withdraw'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='company_account',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='revenue.companyaccount'),
            preserve_default=False,
        ),
    ]
