# Generated by Django 4.2.21 on 2026-02-19 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('revenue', '0016_transaction_company_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
