# Generated by Django 4.2.21 on 2026-02-20 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('revenue', '0018_order_transaction'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='bid_fee',
            new_name='service_fee',
        ),
        migrations.RenameField(
            model_name='orderitem',
            old_name='bid_fee_tax',
            new_name='service_fee_tax',
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='venue',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='year_type',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
