# Generated by Django 4.2.21 on 2026-02-27 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('revenue', '0020_orderitem_canceling_fee_orderitem_commission_fee_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='transaction_type',
            field=models.CharField(choices=[('purchase', 'Purchase'), ('sale', 'Sale'), ('auction', 'Auction'), ('nagare', 'Nagare')], max_length=20),
        ),
    ]
