# Generated by Django 4.2.21 on 2026-03-03 01:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('revenue', '0021_alter_order_transaction_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='model',
        ),
        migrations.AddField(
            model_name='carcategory',
            name='model',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='carcategory',
            name='company',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterUniqueTogether(
            name='carcategory',
            unique_together={('company', 'model', 'user')},
        ),
        migrations.RemoveField(
            model_name='carcategory',
            name='name',
        ),
    ]
