# Generated by Django 4.2.21 on 2026-02-15 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_user_company_address_user_company_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('superadmin', 'Super_Admin')], default='admin', max_length=50),
        ),
    ]
