# Generated by Django 4.2.21 on 2026-02-19 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='business_registration',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
