# Generated by Django 4.2.21 on 2026-02-22 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0006_sparepart_legacy_columns_compat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sparepart',
            name='location',
            field=models.CharField(blank=True, db_column='location', max_length=300),
        ),
        migrations.RenameField(
            model_name='sparepart',
            old_name='location',
            new_name='address',
        ),
        migrations.AddField(
            model_name='sparepart',
            name='brand',
            field=models.CharField(blank=True, default='', editable=False, max_length=120),
        ),
        migrations.AddField(
            model_name='sparepart',
            name='part_number',
            field=models.CharField(blank=True, default='', editable=False, max_length=120),
        ),
    ]
